name: Load secret

on: [push]

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        env:
          MY_KEY: {{ secrets.MY_SECRET }}
        run: |
          echo $MY_KEY    
